language: node_js
node_js:
  - "10"

install: skip
script: skip

before_deploy:
  - yarn
  - yarn codegen
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "./build"
  on:
    branch: master

before_deploy-staging:
  - yarn
  - yarn codegen-staging
  - yarn test
  - yarn build:staging

deploy-staging:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "./build"
  repo: akropolisio/credit-pool-frontend-v2
  on:
    branch: dev

notifications:
  slack: akropolisio:xUhLQpSGEoBylmWK3DW8Kblm
