branches:
  only:
    - master
    - dev

language: node_js
node_js:
  - "10"

install: skip
script: skip

before_deploy:
  - yarn
  - if [ "$TRAVIS_BRANCH" = "master" ]; then yarn codegen; fi
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then yarn codegen:staging; fi
  - yarn test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then yarn build; fi
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then yarn build:staging; fi

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: "./build"
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: "./build"
    repo: akropolisio/credit-pool-frontend-v2
    on:
      branch: dev

notifications:
  slack: akropolisio:xUhLQpSGEoBylmWK3DW8Kblm
