branches:
  only:
    - beta
    - sandbox

language: node_js
node_js:
  - "10"

install: skip
script: skip

before_deploy:
  - yarn
  - if [ "$TRAVIS_BRANCH" = "beta" ]; then yarn codegen; fi
  - if [ "$TRAVIS_BRANCH" = "sandbox" ]; then yarn codegen:staging; fi
  - yarn test
  - if [ "$TRAVIS_BRANCH" = "beta" ]; then yarn build; fi
  - if [ "$TRAVIS_BRANCH" = "sandbox" ]; then yarn build:staging; fi

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: "./build"
    on:
      branch: beta
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: "./build"
    repo: akropolisio/credit-pool-frontend-sandbox
    on:
      branch: sandbox

notifications:
  slack: akropolisio:xUhLQpSGEoBylmWK3DW8Kblm
